# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=3)),
                ('airport_name', models.CharField(max_length=30)),
                ('airport_longitude', models.FloatField()),
                ('airport_latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_from', models.CharField(max_length=50)),
                ('time_from', models.DateTimeField()),
                ('airport_to', models.CharField(max_length=3)),
                ('city_to', models.CharField(max_length=50)),
                ('time_to', models.DateTimeField()),
                ('code_flight', models.CharField(max_length=10)),
                ('enrote', models.BooleanField()),
                ('airport_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.Airport')),
            ],
        ),
    ]
