# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_remove_airport_airport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airport_from',
            field=models.CharField(max_length=3),
        ),
    ]
