# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0003_auto_20171123_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='time_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='time_to',
            field=models.IntegerField(),
        ),
    ]
