# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_auto_20171124_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_city',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
